version: '3'
services:
  mysql:
    image: mysql
    ports:
      - '3306:3306'
    environment:
      MYSQL_ROOT_PASSWORD: 'password'
      MYSQL_USER: 'Kaique'
      MYSQL_PASSWORD: 'password'
      MYSQL_DATABASE: 'creditcard'
